name: Vercel Development Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - dev

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          vercel \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --development \
            --yes \
            --confirm \
            --env VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
            --env VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
            --logs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
